In [ ]:
!nvidia-smi

Mon Apr 21 18:50:53 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L4                      Off |   00000000:00:03.0 Off |                    0 |
| N/A   46C    P8             12W /   72W |       0MiB /  23034MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install pandas>=2.2.3

In [ ]:
!pip install rich>=13.7.1

In [ ]:
# Eksik kütüphaneleri yükle
!pip install git+https://github.com/roboflow/sports.git
!pip install supervision>=0.23.0

  Cloning https://github.com/roboflow/sports.git to /tmp/pip-req-build-rsbf1r6r
  Running command git clone --filter=blob:none --quiet https://github.com/roboflow/sports.git /tmp/pip-req-build-rsbf1r6r
  Resolved https://github.com/roboflow/sports.git to commit 06053616f1f8a8ae1fa936eb00dcdc2e4f888bb1
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.5/181.5 kB 5.8 MB/s eta 0:00:00
  Created wheel for sports: filename=sports-0.1.0-py3-none-any.whl size=10817 sha256=39e652f15298ac0929cd161d73d3afc51706aeeeeffde6c2956e9f8bf69445d6
  Stored in directory: /tmp/pip-ephem-wheel-cache-9fb8br36/wheels/ed/b4/5f/095fc3d469723160503754d469ae8561e31bc82ac660159b2a
Successfully built sports


In [ ]:
!pip show torch  # PyTorch’un yüklü olup olmadığını kontrol et

Name: torch
Version: 2.6.0+cu124
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.11/dist-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, fastai, peft, sentence-transformers, timm, torchaudio, torchvision


In [ ]:
!cp -r /content/jersey-number-pipeline /content/drive/MyDrive/jersey-number-pipeline
!ls /content/drive/MyDrive/jersey-number-pipeline  # Kopyalandığını kontrol et

centroid_reid.py	  legibility_classifier.py  README.md
configuration.py	  license.txt		    reid
data			  main.py		    segment-anything
docs			  models		    setup.py
experiments		  networks.py		    str
gaussian_outliers.py	  number_classifier.py	    str.py
helpers.py		  pose
jersey_number_dataset.py  pose.py


In [ ]:
!pip install SoccerNet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.9/86.9 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.7/67.7 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.3/104.3 MB 20.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 89.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 102.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 9.4 MB/s eta 0:00:00


In [ ]:
# Mevcut reid klasörünü sil
!rm -rf /content/jersey-number-pipeline/reid

# reid klasörünü yeniden oluştur
!mkdir -p /content/jersey-number-pipeline/reid

# Centroid-ReID reposunu klonla
!git clone https://github.com/mikwieczorek/centroids-reid.git /content/jersey-number-pipeline/reid/centroids-reid

# İçeriği kontrol et
!ls /content/jersey-number-pipeline/reid/centroids-reid

Cloning into '/content/jersey-number-pipeline/reid/centroids-reid'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 127 (delta 44), reused 76 (delta 33), pack-reused 3 (from 1)
Receiving objects: 100% (127/127), 69.44 KiB | 546.00 KiB/s, done.
Resolving deltas: 100% (44/44), done.
callbacks  datasets   losses	 requirements.txt  train_base_model.py	utils
config	   inference  modelling  scripts	   train_ctl_model.py
configs    LICENSE    README.md  solver		   train_scripts


In [ ]:
%cd /content/jersey-number-pipeline/reid/centroids-reid
!pip install -r requirements.txt
%cd /content/jersey-number-pipeline

/content/jersey-number-pipeline/reid/centroids-reid
Looking in links: https://download.pytorch.org/whl/torch_stable.html, https://download.pytorch.org/whl/torch_stable.html
  Using cached mlflow-2.21.3-py3-none-any.whl.metadata (30 kB)
  Using cached pytorch_lightning-1.1.4-py3-none-any.whl.metadata (25 kB)
ERROR: Could not find a version that satisfies the requirement torch==1.7.1+cu101 (from versions: 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 1.13.1+cu117.with.pypi.cudnn, 2.0.0, 2.0.0+cpu, 2.0.0+cpu.cxx11.abi, 2.0.0+cu117, 2.0.0+cu117.with.pypi.cudnn, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cpu.cxx11.abi, 2.0.1+cu117, 2.0.1+cu117.with.pypi.cudnn, 2.0.1+cu118, 2.0.1+rocm5.3, 2.0.1+rocm5.4.2, 2.1.0, 2.1.0+cpu, 2.1.0+cpu.cxx11.abi, 2.1.0+cu118, 2.1.0+cu121, 2.1.0+cu121.with.pypi.cudnn, 2.1.0+rocm5.5, 2.1.0+rocm5.6, 2.1.1, 2.1.1+cpu, 2.1.1+cpu.cxx11.abi, 2.1.1+cu118, 2.1.1+cu121, 2.1.1+cu121.with.pypi.cudnn,

In [ ]:
# Models dizinini oluştur
!mkdir -p /content/jersey-number-pipeline/reid/centroids-reid/models

# Centroid-ReID modelini indir (URL’yi repodan bul)
!wget "CENTROID_REID_MODEL_URL" -O /content/jersey-number-pipeline/reid/centroids-reid/models/centroids_reid.pth

# Dosyanın indirildiğini kontrol et
!ls /content/jersey-number-pipeline/reid/centroids-reid/models

--2025-04-22 05:08:00--  http://centroid_reid_model_url/
Resolving centroid_reid_model_url (centroid_reid_model_url)... failed: Name or service not known.
wget: unable to resolve host address ‘centroid_reid_model_url’
centroids_reid.pth


In [ ]:
# Drive’a kopyala
!cp -r /content/jersey-number-pipeline/reid/centroids-reid/models /content/drive/MyDrive/jersey-models/centroids-reid
!ls /content/drive/MyDrive/jersey-models/centroids-reid

centroids_reid.pth


In [ ]:
# reid klasörünün içeriğini kontrol et
!ls /content/jersey-number-pipeline/reid

# centroids-reid klasörünün içeriğini kontrol et
!ls /content/jersey-number-pipeline/reid/centroids-reid

# models dizininin içeriğini kontrol et
!ls /content/jersey-number-pipeline/reid/centroids-reid/models

centroids-reid
callbacks  inference  models		solver		     utils
config	   LICENSE    README.md		train_base_model.py
configs    losses     requirements.txt	train_ctl_model.py
datasets   modelling  scripts		train_scripts
centroids_reid.pth


In [ ]:
# Drive’daki boş reid klasörünü sil
!rm -rf /content/drive/MyDrive/jersey-models/reid

# Tüm reid klasörünü tekrar Drive’a kopyala
!cp -r /content/jersey-number-pipeline/reid /content/drive/MyDrive/jersey-models/reid

# Kopyalandığını kontrol et
!ls /content/drive/MyDrive/jersey-models/reid
!ls /content/drive/MyDrive/jersey-models/reid/centroids-reid
!ls /content/drive/MyDrive/jersey-models/reid/centroids-reid/models

centroids-reid
callbacks  inference  models		solver		     utils
config	   LICENSE    README.md		train_base_model.py
configs    losses     requirements.txt	train_ctl_model.py
datasets   modelling  scripts		train_scripts
centroids_reid.pth


In [ ]:
# Yerel ortama geçici bir dizin oluştur
!mkdir -p /content/temp

# ViTPose reposunu klonla
!git clone https://github.com/ViTAE-Transformer/ViTPose.git /content/temp/ViTPose

# İçeriği kontrol et
!ls /content/temp/ViTPose

Cloning into '/content/temp/ViTPose'...
remote: Enumerating objects: 1859, done.
remote: Counting objects: 100% (1041/1041), done.
remote: Compressing objects: 100% (316/316), done.
remote: Total 1859 (delta 794), reused 725 (delta 725), pack-reused 818 (from 1)
Receiving objects: 100% (1859/1859), 10.75 MiB | 18.22 MiB/s, done.
Resolving deltas: 100% (958/958), done.
CITATION.cff  docs     MANIFEST.in	pytest.ini	  resources  tools
configs       figures  mmcv_custom	README.md	  setup.cfg
demo	      LICENSE  mmpose		requirements	  setup.py
docker	      logs     model-index.yml	requirements.txt  tests


In [ ]:
# Drive’daki pose dizinini oluştur (eğer yoksa)
!mkdir -p /content/drive/MyDrive/jersey-number-pipeline/pose

# ViTPose reposunu Drive’a kopyala
!cp -r /content/temp/ViTPose /content/drive/MyDrive/jersey-number-pipeline/pose/ViTPose

# Kopyalandığını kontrol et
!ls /content/drive/MyDrive/jersey-number-pipeline/pose/ViTPose

CITATION.cff  docs     MANIFEST.in	pytest.ini	  resources  tools
configs       figures  mmcv_custom	README.md	  setup.cfg
demo	      LICENSE  mmpose		requirements	  setup.py
docker	      logs     model-index.yml	requirements.txt  tests


In [ ]:
# Checkpoints dizinini oluştur
!mkdir -p /content/jersey-number-pipeline/pose/ViTPose/checkpoints

# ViTPose modelini indir
!wget "https://github.com/ViTAE-Transformer/ViTPose/releases/download/v0.1/vitpose-b.pth" -O /content/jersey-number-pipeline/pose/ViTPose/checkpoints/vitpose.pth

# Dosyanın indirildiğini kontrol et
!ls /content/jersey-number-pipeline/pose/ViTPose/checkpoints

--2025-04-22 05:18:17--  https://github.com/ViTAE-Transformer/ViTPose/releases/download/v0.1/vitpose-b.pth
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-04-22 05:18:18 ERROR 404: Not Found.

vitpose.pth


In [ ]:
# Drive’daki checkpoints dizinini oluştur ve kopyala
!mkdir -p /content/drive/MyDrive/jersey-number-pipeline/pose/ViTPose/checkpoints
!cp -r /content/jersey-number-pipeline/pose/ViTPose/checkpoints /content/drive/MyDrive/jersey-number-pipeline/pose/ViTPose/

# Kopyalandığını kontrol et
!ls /content/drive/MyDrive/jersey-number-pipeline/pose/ViTPose/checkpoints

vitpose.pth


In [ ]:
# PARSeq reposunu klonla
!git clone https://github.com/baudm/parseq.git /content/jersey-number-pipeline/parseq

# İçeriği kontrol et
!ls /content/jersey-number-pipeline/parseq

Cloning into '/content/jersey-number-pipeline/parseq'...
remote: Enumerating objects: 612, done.
remote: Counting objects: 100% (307/307), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 612 (delta 245), reused 197 (delta 197), pack-reused 305 (from 3)
Receiving objects: 100% (612/612), 1.34 MiB | 3.46 MiB/s, done.
Resolving deltas: 100% (346/346), done.
bench.py     demo_images  Makefile	  README.md	strhub	 train.py
configs      hubconf.py   NOTICE	  read.py	test.py  tune.py
Datasets.md  LICENSE	  pyproject.toml  requirements	tools


In [ ]:
%cd /content/jersey-number-pipeline/parseq
!pip install -r requirements.txt
%cd /content/jersey-number-pipeline

/content/jersey-number-pipeline/parseq
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
/content/jersey-number-pipeline


In [ ]:
# Drive’daki jersey-number-pipeline dizinine kopyala
!cp -r /content/jersey-number-pipeline/parseq /content/drive/MyDrive/jersey-number-pipeline/parseq

# Kopyalandığını kontrol et
!ls /content/drive/MyDrive/jersey-number-pipeline/parseq

bench.py     demo_images  Makefile	  README.md	strhub	 train.py
configs      hubconf.py   NOTICE	  read.py	test.py  tune.py
Datasets.md  LICENSE	  pyproject.toml  requirements	tools


In [ ]:
# Models dizinini oluştur
!mkdir -p /content/jersey-number-pipeline/models

# Orijinal PARSeq modelini indir
!wget "https://github.com/baudm/parseq/releases/download/v1.0.0/parseq.pth" -O /content/jersey-number-pipeline/models/parseq.pth

# Dosyanın indirildiğini kontrol et
!ls /content/jersey-number-pipeline/models

--2025-04-22 05:23:49--  https://github.com/baudm/parseq/releases/download/v1.0.0/parseq.pth
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-04-22 05:23:50 ERROR 404: Not Found.

parseq.pth


In [ ]:
# gdown’u yükle (Google Drive’dan dosya indirmek için)
!pip install gdown

# SoccerNet fine-tuned PARSeq modelini indir
!gdown --id 1AK_GnM6pIYyfIf3tBYSKIyR3Fa3Z46Cx -O /content/jersey-number-pipeline/models/parseq_jersey_soccer.pth

# Dosyanın indirildiğini kontrol et
!ls /content/jersey-number-pipeline/models

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1AK_GnM6pIYyfIf3tBYSKIyR3Fa3Z46Cx
From (redirected): https://drive.google.com/uc?id=1AK_GnM6pIYyfIf3tBYSKIyR3Fa3Z46Cx&confirm=t&uuid=10784b2a-db93-437b-a165-b9e9398f249b
To: /content/jersey-number-pipeline/models/parseq_jersey_soccer.pth
100% 95.4M/95.4M [00:01<00:00, 61.4MB/s]
parseq_jersey_soccer.pth  parseq.pth


In [ ]:
# Drive’daki models dizinini oluştur ve kopyala
!mkdir -p /content/drive/MyDrive/jersey-number-pipeline/models
!cp -r /content/jersey-number-pipeline/models /content/drive/MyDrive/jersey-number-pipeline/

# Kopyalandığını kontrol et
!ls /content/drive/MyDrive/jersey-number-pipeline/models

parseq_jersey_soccer.pth  parseq.pth


In [ ]:
!wget "LEGIBILITY_MODEL_URL" -O /content/jersey-number-pipeline/models/resnet34_legibility.pth
!cp -r /content/jersey-number-pipeline/models /content/drive/MyDrive/jersey-number-pipeline/models

--2025-04-22 05:25:38--  http://legibility_model_url/
Resolving legibility_model_url (legibility_model_url)... failed: Name or service not known.
wget: unable to resolve host address ‘legibility_model_url’


In [ ]:
!scenedetect --input /content/drive/MyDrive/videos/match_video.mp4 detect-content -t 30 list-scenes
!cp /content/match_video-Scenes.csv /content/drive/MyDrive/match_video-Scenes.csv
!ls /content/drive/MyDrive/

/bin/bash: line 1: scenedetect: command not found
cp: cannot stat '/content/match_video-Scenes.csv': No such file or directory
 aktiviteler.csv	       segment-anything
'Colab Notebooks'	       sehirler.csv
 images-20250418T094133Z-001   sehir_tatil_turu_baglanti.csv
 jersey-data		       tatil_turleri.csv
 jersey-number-pipeline        tatil_verileri_hotel_details_1500_20250308.csv
 jersey_recognition	       tatil_verileri_with_distance_rating_20250308.csv
 odalar.csv		       ulasim.csv
 oteller.csv		       ulkeler.csv
 ProjectPart1-Scenario1.xlsx   Untitled2.ipynb
 ProjectPart1-Scenario2.xlsx   videos
 ProjectPart1-Scenario3.xlsx


In [ ]:
# scenedetect’i yükle
!pip install scenedetect

# Sahneleri tespit et
!scenedetect --input /content/drive/MyDrive/videos/match_video.mp4 detect-content -t 30 list-scenes

# Sahne dosyasını Drive’a kopyala
!cp /content/jersey-number-pipeline/match_video-Scenes.csv /content/drive/MyDrive/match_video-Scenes.csv

# Kontrol et
!ls /content/drive/MyDrive/

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 4.1 MB/s eta 0:00:00
[PySceneDetect] PySceneDetect 0.6.6
[PySceneDetect] Detecting scenes...
  Detected: 84 | Progress: 100% 12168/12169 [00:11<00:00, 1058.19frames/s]
[PySceneDetect] Processed 12168 frames in 11.5 seconds (average 1057.82 FPS).
[PySceneDetect] Detected 85 scenes, average shot length 5.7 seconds.
[PySceneDetect] Writing scene list to CSV file:
  match_video-Scenes.csv
[PySceneDetect] Scene List:
-----------------------------------------------------------------------
 | Scene # | Start Frame |  Start Time  |  End Frame  |   End Time   |
-----------------------------------------------------------------------
 |      1  |           1 | 00:00:00.000 |         160 | 00:00:06.399 |
 |      2  |         161 | 00:00:06.399 |         207 | 00:00:08.279 |
 |      3  |         208 | 00:00:08.279 |         267 | 00:00:10.679 |
 |      4  |         268 | 00:00:10.679 |         710 | 00:00:28.398 |
 |      5  |         711 |

In [ ]:
!cp /content/jersey-number-pipeline/match_video-Scenes.csv /content/drive/MyDrive/match_video-Scenes.csv

In [ ]:
import cv2
import numpy as np
from segment_anything import SamPredictor, sam_model_registry

# SAM modelini yükle
sam = sam_model_registry["vit_h"](checkpoint="/content/jersey-number-pipeline/segment_anything/sam_vit_h_4b8939.pth")
predictor = SamPredictor(sam)

def segment_player(image, bbox):
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    predictor.set_image(image_rgb)
    masks, _, _ = predictor.predict(box=bbox, multimask_output=False)
    return masks[0]

In [ ]:
import sys
sys.path.append('/content/drive/MyDrive/jersey_number_pipeline')



In [ ]:
import cv2
import numpy as np
import pandas as pd
import pickle
from segment_anything import SamPredictor, sam_model_registry
from jersey_number_pipeline import JerseyNumberPipeline

# SAM modelini yükle
sam = sam_model_registry["vit_h"](checkpoint="/content/jersey_number_pipeline/segment_anything/sam_vit_h_4b8939.pth")
predictor = SamPredictor(sam)

def segment_player(image, bbox):
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    predictor.set_image(image_rgb)
    masks, _, _ = predictor.predict(box=bbox, multimask_output=False)
    return masks[0]

# Pipeline’ı yükle
pipeline = JerseyNumberPipeline(
    legible_classifier_path='/content/jersey-number-pipeline/models/resnet34_legibility.pth',
    parseq_model_path='/content/jersey-number-pipeline/models/parseq_jersey_soccer.pth',
    reid_model_path='/content/jersey-number-pipeline/reid/centroids-reid/models/centroids_reid.pth',
    pose_model_path='/content/jersey-number-pipeline/pose/ViTPose/checkpoints/vitpose.pth'
)

# Sahne zamanlarını oku, ilk satırı atla
scenes_df = pd.read_csv('/content/drive/MyDrive/match_video-Scenes.csv', header=1)
scenes = scenes_df[['Start Time (seconds)', 'End Time (seconds)']].values

# Videoyu oku
video_path = '/content/drive/MyDrive/videos/match_video.mp4'
cap = cv2.VideoCapture(video_path)
fps = cap.get(cv2.CAP_PROP_FPS)

# Her sahne için tracklet oluştur
tracklets = []
for idx, (start_time, end_time) in enumerate(scenes):
    print(f"Sahne {idx + 1} işleniyor: {start_time}s - {end_time}s")

    start_frame = int(start_time * fps)
    end_frame = int(end_time * fps)
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    frames = []
    for frame_idx in range(start_frame, end_frame):
        ret, frame = cap.read()
        if not ret:
            break
        frames.append(frame)

    # Sahne içinde tracklet oluştur
    scene_tracklets = pipeline.process_frames(frames)

    # SAM ile segmentasyon yap
    for tracklet in scene_tracklets:
        for frame_idx, result in tracklet.items():
            bbox = result['bbox']
            mask = segment_player(frames[frame_idx - start_frame], bbox)
            result['mask'] = mask

    tracklets.append(scene_tracklets)

    # Her sahneyi işledikten sonra tracklet’leri Drive’a kaydet
    with open(f'/content/drive/MyDrive/tracklets_scene_{idx}.pkl', 'wb') as f:
        pickle.dump(scene_tracklets, f)

cap.release()
print("Tracklet’ler oluşturuldu ve Drive’a kaydedildi.")

ImportError: cannot import name 'JerseyNumberPipeline' from 'jersey_number_pipeline' (unknown location)

In [ ]:
!ls /content/drive/MyDrive/jersey_number_pipeline


centroid_reid.py	  legibility_classifier.py  pose.py
configuration.py	  license.txt		    README.md
data			  main.py		    reid
docs			  models		    segment-anything
experiments		  networks.py		    setup.py
gaussian_outliers.py	  number_classifier.py	    str
helpers.py		  parseq		    str.py
jersey_number_dataset.py  pose


In [ ]:
!grep -rn "class JerseyNumberPipeline" /content/drive/MyDrive/jersey_number_pipeline


^C


In [ ]:
import cv2
import os
import pandas as pd

# Sahne zamanlarını oku
scenes_df = pd.read_csv('/content/drive/MyDrive/match_video-Scenes.csv', header=1)
scenes = scenes_df[['Start Time (seconds)', 'End Time (seconds)']].values

# Video yolu
video_path = '/content/drive/MyDrive/videos/match_video.mp4'
cap = cv2.VideoCapture(video_path)
fps = cap.get(cv2.CAP_PROP_FPS)

# Kareleri kaydetmek için dizin oluştur
base_output_dir = '/content/jersey_number_pipeline/data/custom_video/images'
os.makedirs(base_output_dir, exist_ok=True)

# Her sahne için kareleri çıkar
for idx, (start_time, end_time) in enumerate(scenes):
    tracklet_dir = f'{base_output_dir}/tracklet_{idx}'
    os.makedirs(tracklet_dir, exist_ok=True)

    start_frame = int(start_time * fps)
    end_frame = int(end_time * fps)
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    frame_idx = 0
    for i in range(start_frame, end_frame):
        ret, frame = cap.read()
        if not ret:
            break
        cv2.imwrite(f'{tracklet_dir}/frame_{frame_idx:04d}.jpg', frame)
        frame_idx += 1

cap.release()
print("Kareler çıkarıldı ve kaydedildi.")

Kareler çıkarıldı ve kaydedildi.


In [ ]:
%%writefile /content/jersey_number_pipeline/configuration.py
dataset = {
    'SoccerNet': {
        'root_dir': '/content/jersey_number_pipeline/data',
        'working_dir': '/content/drive/MyDrive/jersey-working-dir',
        'legibility_model': '/content/jersey_number_pipeline/models/resnet34_legibility.pth',
        'legibility_model_arch': 'resnet34',
        'str_model': '/content/jersey_number_pipeline/models/parseq_jersey_soccer.pth',
        'test': {
            'images': 'custom_video/images',
            'feature_output_folder': 'custom_video/features',
            'soccer_ball_list': 'custom_video/soccer_ball_list.json',
            'legible_result': 'custom_video/legible_results.json',
            'illegible_result': 'custom_video/illegible_results.json',
            'pose_input_json': 'custom_video/pose_input.json',
            'pose_output_json': 'custom_video/pose_output.json',
            'crops_folder': 'custom_video/crops',
            'jersey_id_result': 'custom_video/jersey_id_predictions.json',
            'final_result': 'custom_video/final_results.json',
            'gt': 'custom_video/test_gt.json',
            'gauss_filtered': 'custom_video/gauss_filtered.json',
            'sim_filtered': 'custom_video/sim_filtered.json'
        }
    }
}

str_home = '/content/jersey_number_pipeline/parseq'
str_env = 'parseq_env'
reid_env = 'reid_env'
reid_script = '/content/jersey_number_pipeline/reid/centroids-reid/reid_script.py'
pose_env = 'pose_env'
pose_home = '/content/jersey_number_pipeline/pose/ViTPose'

Writing /content/jersey_number_pipeline/configuration.py


In [ ]:
%%writefile /content/jersey_number_pipeline/helpers.py
import json
import os
import cv2
import numpy as np

def identify_soccer_balls(image_dir, output_file):
    # Soccer ball tespiti için basit bir yer tutucu
    ball_tracks = []
    with open(output_file, 'w') as f:
        json.dump({'ball_tracks': ball_tracks}, f)
    return True

def evaluate_legibility(gt_path, illegible_path, legible_dict, soccer_ball_list=None):
    print("Evaluating legibility...")
    return True

def generate_json(image_paths, output_json):
    with open(output_json, 'w') as f:
        json.dump({'images': image_paths}, f)

def generate_crops(pose_json, crops_dir, legible_results):
    os.makedirs(crops_dir, exist_ok=True)
    return True

def process_jersey_id_predictions(result_file, useBias=True):
    try:
        with open(result_file, 'r') as f:
            results = json.load(f)
    except FileNotFoundError:
        results = {}
    results_dict = {str(k): v for k, v in results.items()}
    analysis_results = results
    return results_dict, analysis_results

def evaluate_results(pred_dict, gt_dict, full_results=None):
    print("Evaluating results...")
    return True

Writing /content/jersey_number_pipeline/helpers.py


In [ ]:
# Google Drive’ı bağla
from google.colab import drive
drive.mount('/content/drive')

# Yerel sam reposunu Drive’a taşı
!mv /content/jersey_number_pipeline/sam /content/drive/MyDrive/jersey_number_pipeline/sam

# Taşımanın başarılı olduğunu kontrol et
!ls /content/drive/MyDrive/jersey_number_pipeline/sam

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
example  img  LICENSE  __pycache__  README.md  sam.py


In [ ]:
# jersey-number-pipeline dizinine geç
%cd /content/jersey_number_pipeline

# davda54/sam reposunu klonla
!git clone https://github.com/davda54/sam.git sam

# Dizin yapısını kontrol et
!ls /content/jersey_number_pipeline/sam

/content/jersey-number-pipeline
fatal: destination path 'sam' already exists and is not an empty directory.
example  img  LICENSE  README.md  sam.py


In [ ]:
# Çalışma dizinini değiştir
%cd /content/drive/MyDrive/jersey_number_pipeline

# Mevcut dizini doğrula
!pwd

/content/drive/MyDrive/jersey_number_pipeline
/content/drive/MyDrive/jersey_number_pipeline


In [ ]:
# Çalışma dizinini kontrol et
%cd /content/drive/MyDrive/jersey_number_pipeline
!pwd

# Gerekli modül yollarını ayarla
import sys
sys.path.append('/content/drive/MyDrive/jersey_number_pipeline')

# soccer_net_pipeline’ı çalıştır
import argparse
from main import soccer_net_pipeline

# Argümanları manuel oluştur
args = argparse.Namespace(
    dataset='SoccerNet',
    part='test',
    train_str=False,
    pipeline={
        'soccer_ball_filter': True,
        'feat': True,
        'filter': True,
        'legible': True,
        'legible_eval': False,
        'pose': True,
        'crops': True,
        'str': True,
        'combine': True,
        'eval': False
    }
)

# Çalışma dizinini ayarla
import os
os.makedirs('/content/drive/MyDrive/jersey-working-dir/custom_video', exist_ok=True)

# Pipeline’ı çalıştır
soccer_net_pipeline(args)

# Sonuçları kontrol et
!ls /content/drive/MyDrive/jersey-working-dir/custom_video

/content/drive/MyDrive/jersey_number_pipeline
/content/drive/MyDrive/jersey_number_pipeline
Determine soccer ball
Done determine soccer ball
Generate features
Done generating features
soccer_ball_list.json


In [ ]:
import cv2
import pandas as pd
import numpy as np
import pickle
import glob
import torch
import torchvision.transforms as transforms
from PIL import Image

# PARSeq ve Legibility Classifier için gerekli modülleri yükle
import sys
sys.path.append('/content/jersey_number_pipeline/parseq')
from parseq.models.parseq import PARSeq
from parseq.utils import load_checkpoint

# Bağımlılıkları yükle (önceden yapılmadıysa)
!pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 torchaudio==2.3.1+cu121 -f https://download.pytorch.org/whl/torch_stable.html
!pip install pytorch-lightning --upgrade
!pip install einops mlflow opencv-python

# Cihaz ayarı (GPU varsa kullan)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# PARSeq modelini yükle
parseq_model_path = '/content/jersey_number_pipeline/models/parseq_jersey_soccer.pth'
parseq = PARSeq.load_from_checkpoint(parseq_model_path).to(device)
parseq.eval()

# Legibility Classifier modelini yükle (ResNet34 tabanlı)
legibility_model_path = '/content/jersey_number_pipeline/models/resnet34_legibility.pth'
legibility_classifier = torch.load(legibility_model_path, map_location=device)
legibility_classifier.eval()

# Görüntü ön işleme için transform
transform = transforms.Compose([
    transforms.Resize((32, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def process_jersey_region(frame, bbox):
    """Bounding box içindeki forma bölgesini kırp ve ön işle."""
    x, y, w, h = bbox
    jersey_region = frame[y:y+h, x:x+w]
    jersey_region = cv2.cvtColor(jersey_region, cv2.COLOR_BGR2RGB)
    jersey_region = Image.fromarray(jersey_region)
    jersey_region = transform(jersey_region).unsqueeze(0).to(device)
    return jersey_region

def is_legible(jersey_region):
    """Forma numarasının okunabilirliğini kontrol et."""
    with torch.no_grad():
        logits = legibility_classifier(jersey_region)
        prob = torch.softmax(logits, dim=1)
        legible_prob = prob[:, 1].item()  # Okunabilir olma olasılığı
        return legible_prob > 0.5  # Eşik: %50

def read_jersey_number(jersey_region):
    """Forma numarasını PARSeq ile oku."""
    with torch.no_grad():
        logits = parseq(jersey_region)
        pred = parseq.decode(logits)
        return pred[0] if pred else 'N/A'

# Tracklet’ları yükle
tracklet_files = glob.glob('/content/drive/MyDrive/tracklets_scene_*.pkl')
tracklets = []
for file in tracklet_files:
    with open(file, 'rb') as f:
        scene_tracklets = pickle.load(f)
        tracklets.append(scene_tracklets)

print(f"{len(tracklets)} sahne için tracklet’lar yüklendi.")

# Video ve sahne bilgilerini oku
video_path = '/content/drive/MyDrive/videos/match_video.mp4'
cap = cv2.VideoCapture(video_path)
fps = cap.get(cv2.CAP_PROP_FPS)

scenes_df = pd.read_csv('/content/drive/MyDrive/match_video-Scenes.csv')
scenes = scenes_df[['Start Time (seconds)', 'End Time (seconds)']].values

# Çıktı CSV dosyası
output_csv = "/content/jersey_numbers.csv"
with open(output_csv, "w") as f:
    f.write("second,jersey_number,bbox\n")

# Her sahne için tracklet’ları işle
for idx, (start_time, end_time) in enumerate(scenes):
    start_frame = int(start_time * fps)
    end_frame = int(end_time * fps)
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    scene_tracklets = tracklets[idx]

    for frame_idx in range(start_frame, end_frame):
        ret, frame = cap.read()
        if not ret:
            break

        second = frame_idx / fps
        for tracklet in scene_tracklets:
            if frame_idx in tracklet:
                result = tracklet[frame_idx]
                bbox = result['bbox']

                # Forma bölgesini kırp ve ön işle
                jersey_region = process_jersey_region(frame, bbox)

                # Okunabilirlik kontrolü
                if is_legible(jersey_region):
                    # Forma numarasını oku
                    jersey_number = read_jersey_number(jersey_region)
                    if jersey_number != 'N/A':
                        with open(output_csv, "a") as f:
                            f.write(f"{second:.2f},{jersey_number},{bbox}\n")

cap.release()
print(f"Forma numaraları {output_csv} dosyasına kaydedildi.")
# Drive’a kopyala
!cp /content/jersey_numbers.csv /content/drive/MyDrive/

ModuleNotFoundError: No module named 'parseq.models'

In [ ]:
# Örnek bir görüntüyü oku
import cv2
image_path = '/content/drive/MyDrive/jersey_number_pipeline/data/custom_video/images/tracklet_0/frame_0000.jpg'
image = cv2.imread(image_path)
print(f"Image: {image}")

Image: [[[120  64  69]
  [128  72  77]
  [155  97 102]
  ...
  [130 113  80]
  [128 109  76]
  [116  97  62]]

 [[124  74  76]
  [131  81  83]
  [164 111 114]
  ...
  [145 127  96]
  [137 118  85]
  [128 109  74]]

 [[ 83  45  41]
  [104  66  62]
  [132  88  87]
  ...
  [111  96  64]
  [110  92  61]
  [118 101  68]]

 ...

 [[ 40 115 117]
  [ 39 114 116]
  [ 37 114 116]
  ...
  [ 43  88  99]
  [ 43  88  99]
  [ 43  88  99]]

 [[ 42 118 117]
  [ 41 117 116]
  [ 40 116 115]
  ...
  [ 43  85  97]
  [ 43  85  97]
  [ 43  85  97]]

 [[ 29 105 104]
  [ 29 105 104]
  [ 29 105 104]
  ...
  [ 31  73  85]
  [ 33  73  85]
  [ 33  73  85]]]


In [ ]:
%%writefile /content/drive/MyDrive/jersey_number_pipeline/helpers.py
import os
import cv2
import json

def identify_soccer_balls(image_dir, soccer_ball_list):
    print(f"### identify_soccer_balls fonksiyonu başladı ###")
    print(f"image_dir: {image_dir}")

    # image_dir mevcut mu kontrol et
    if not os.path.exists(image_dir):
        print(f"Hata: image_dir ({image_dir}) mevcut değil!")
        return False

    tracklets = os.listdir(image_dir)
    print(f"Tracklets found: {tracklets}")

    if not tracklets:
        print("Hata: image_dir içinde tracklet bulunamadı!")
        ball_json = {'ball_tracks': []}
        with open(soccer_ball_list, 'w') as f:
            json.dump(ball_json, f)
        return False

    ball_tracks = []
    for track in tracklets:
        track_dir = os.path.join(image_dir, track)
        print(f"Track: {track}, Track_dir: {track_dir}")

        # track_dir mevcut mu kontrol et
        if not os.path.isdir(track_dir):
            print(f"Hata: {track_dir} bir dizin değil!")
            continue

        images = os.listdir(track_dir)
        print(f"Images in {track}: {images}")

        if len(images) == 0:
            print(f"Uyarı: {track} klasöründe görüntü bulunamadı!")
            continue

        image_path = os.path.join(track_dir, images[0])
        print(f"Image path: {image_path}")

        # image_path mevcut mu kontrol et
        if not os.path.exists(image_path):
            print(f"Hata: {image_path} dosyası mevcut değil!")
            continue

        image = cv2.imread(image_path)
        if image is None:
            print(f"Hata: {image_path} okunamadı!")
            continue

        try:
            print(f"Image shape: {image.shape}")
            if image.shape[0] < 50 or image.shape[1] < 50:  # Soccer ball images are typically small
                ball_tracks.append(track)
                print(f"{track} bir futbol topu olarak sınıflandırıldı.")
        except Exception as e:
            print(f"Hata: {track} işlenirken bir sorun oluştu: {e}")
            continue

    ball_json = {'ball_tracks': ball_tracks}
    with open(soccer_ball_list, 'w') as f:
        json.dump(ball_json, f)
    print(f"Soccer ball list saved: {soccer_ball_list}")
    print(f"### identify_soccer_balls fonksiyonu tamamlandı ###")
    return True

# Diğer fonksiyonlar
def generate_json(all_files, output_json):
    print(f"### generate_json fonksiyonu başladı ###")
    data = []
    for file_path in all_files:
        data.append({"image_path": file_path})
    with open(output_json, 'w') as f:
        json.dump(data, f)
    print(f"JSON saved: {output_json}")
    print(f"### generate_json fonksiyonu tamamlandı ###")

def evaluate_legibility(gt_path, illegible_path, legible_dict, soccer_ball_list=None):
    print(f"### evaluate_legibility fonksiyonu başladı ###")
    print("Evaluating legibility...")
    print(f"### evaluate_legibility fonksiyonu tamamlandı ###")

def generate_crops(output_json, crops_destination_dir, legible_results):
    print(f"### generate_crops fonksiyonu başladı ###")
    print(f"Generating crops in {crops_destination_dir}...")
    print(f"### generate_crops fonksiyonu tamamlandı ###")

def process_jersey_id_predictions(result_file, useBias=True):
    print(f"### process_jersey_id_predictions fonksiyonu başladı ###")
    with open(result_file, 'r') as f:
        results = json.load(f)
    print(f"### process_jersey_id_predictions fonksiyonu tamamlandı ###")
    return results, None

def evaluate_results(consolidated_dict, gt_dict, full_results=None):
    print(f"### evaluate_results fonksiyonu başladı ###")
    print("Evaluating results...")
    print(f"### evaluate_results fonksiyonu tamamlandı ###")

Overwriting /content/drive/MyDrive/jersey_number_pipeline/helpers.py


In [ ]:
import cv2
import os
import pandas as pd

# Sahne zamanlarını oku
scenes_df = pd.read_csv('/content/drive/MyDrive/match_video-Scenes.csv', header=1)
scenes = scenes_df[['Start Time (seconds)', 'End Time (seconds)']].values

# Video yolu
video_path = '/content/drive/MyDrive/videos/match_video.mp4'
cap = cv2.VideoCapture(video_path)
fps = cap.get(cv2.CAP_PROP_FPS)

# Kareleri kaydetmek için dizin oluştur
base_output_dir = '/content/drive/MyDrive/jersey_number_pipeline/data/custom_video/images'
os.makedirs(base_output_dir, exist_ok=True)

# Her sahne için kareleri çıkar
for idx, (start_time, end_time) in enumerate(scenes):
    tracklet_dir = f'{base_output_dir}/tracklet_{idx}'
    os.makedirs(tracklet_dir, exist_ok=True)

    start_frame = int(start_time * fps)
    end_frame = int(end_time * fps)
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    frame_idx = 0
    for i in range(start_frame, end_frame):
        ret, frame = cap.read()
        if not ret:
            break
        cv2.imwrite(f'{tracklet_dir}/frame_{frame_idx:04d}.jpg', frame)
        frame_idx += 1

cap.release()
print("Kareler çıkarıldı ve kaydedildi.")

# Karelerin kaydedildiğini kontrol et
!ls -R /content/drive/MyDrive/jersey_number_pipeline/data/custom_video/images

Kareler çıkarıldı ve kaydedildi.
/content/drive/MyDrive/jersey_number_pipeline/data/custom_video/images:
tracklet_0   tracklet_22  tracklet_36  tracklet_5   tracklet_63  tracklet_77
tracklet_1   tracklet_23  tracklet_37  tracklet_50  tracklet_64  tracklet_78
tracklet_10  tracklet_24  tracklet_38  tracklet_51  tracklet_65  tracklet_79
tracklet_11  tracklet_25  tracklet_39  tracklet_52  tracklet_66  tracklet_8
tracklet_12  tracklet_26  tracklet_4   tracklet_53  tracklet_67  tracklet_80
tracklet_13  tracklet_27  tracklet_40  tracklet_54  tracklet_68  tracklet_81
tracklet_14  tracklet_28  tracklet_41  tracklet_55  tracklet_69  tracklet_82
tracklet_15  tracklet_29  tracklet_42  tracklet_56  tracklet_7	 tracklet_83
tracklet_16  tracklet_3   tracklet_43  tracklet_57  tracklet_70  tracklet_84
tracklet_17  tracklet_30  tracklet_44  tracklet_58  tracklet_71  tracklet_9
tracklet_18  tracklet_31  tracklet_45  tracklet_59  tracklet_72
tracklet_19  tracklet_32  tracklet_46  tracklet_6   tracklet_73


In [ ]:
!pip install mmcv-full==1.7.1 mmpose==1.1.0 opencv-python einops gdown
!pip install torch==2.0.1 torchvision torchaudio


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 605.4/605.4 kB 32.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 75.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 464.4/464.4 kB 38.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 125.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 98.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 58.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
from mmpose.apis import init_pose_model, inference_topdown
from mmpose.structures import merge_data_samples
import cv2
import numpy as np
from PIL import Image

config_file = '/content/drive/MyDrive/jersey-number-pipeline/pose/ViTPose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose-huge-simple-coco-256x192.py'
checkpoint_file = '/content/drive/MyDrive/jersey-number-pipeline/pose/ViTPose/checkpoints/vitpose.pth'

pose_model = init_pose_model(config_file, checkpoint_file, device='cuda')


ModuleNotFoundError: No module named 'mmpose'